config/routes.rb
Rails.application.routes.draw do
  get 'cacti/index'

  resources :cacti
 
  root 'cacti#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cactus.rb
class Cactus < ApplicationRecord
    validates :common_name, presence: true
    validates :genus, presence: true
    validates :species, presence: true
    validates :imageUrl, presence: true
    validates :hardiness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cacti_controller.rb
class CactiController < ApplicationController

    # Correct order is index, show, new, edit, create, update, destroy
    
    def index
        @cacti = Cactus.all
    end

    def show
        @cactus = Cactus.find(params[:id])
    end
    
    def new
        @cactus = Cactus.new
    end

    def edit
        @cactus = Cactus.find(params[:id])
    end

    def create
        @cactus = Cactus.new(cacti_params)
       
        @cactus.save
        redirect_to @cactus
    end

    def update
        @cactus = Cactus.find(params[:id])

        if @cactus.update(cacti_params)
            redirect_to @cactus
        else
            render 'edit'
        end
    end

    def destroy
        @cactus = Cactus.find(params[:id])
        @cactus.destroy
       
        render 'index'      
    end

    private
        def cacti_params
            params.require(:cactus).permit(:common_name, :genus, :species, :cultivar, :imageUrl, :light_requirements, 
            :soil_requirements, :water_requirements, :fruit, :flower, :hardiness, :fertilizer, :propagation,
            :growth_rate, :max_size, :interesting_facts)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cacti_helper.rb
module CactiHelper
end

app/views/cacti/_form.html.erb
<%= form_with model: @cactus, local: true do |form| %>
 
    <% if @cactus.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@cactus.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @cactus.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
        <%= form.label :common_name %><br>
        <%= form.text_field :common_name %>
    </p>
    <p>
        <%= form.label :genus %><br>
        <%= form.text_field :genus %>
    </p>
    <p>
        <%= form.label :species %><br>
        <%= form.text_field :species %>
    </p>
    <p>
        <%= form.label :cultivar %><br>
        <%= form.text_field :cultivar %>
    </p>
    <p>
        <%= form.label :imageUrl %><br>
        <%= form.text_field :imageUrl %>
    </p>
    <p>
        <%= form.label :light_requirements %><br>
        <%= form.text_area :light_requirements %>
    </p>
    <p>
        <%= form.label :soil_requirements %><br>
        <%= form.text_area :soil_requirements %>
    </p>
    <p>
        <%= form.label :water_requirements %><br>
        <%= form.text_area :water_requirements %>
    </p>
    <p>
        <%= form.label :fruit %><br>
        <%= form.text_area :fruit %>
    </p>
    <p>
        <%= form.label :flower %><br>
        <%= form.text_area :flower %>
    </p>
    <p>
        <%= form.label :hardiness %><br>
        <%= form.text_area :hardiness %>
    </p>
    <p>
        <%= form.label :fertilizer %><br>
        <%= form.text_area :fertilizer %>
    </p>
    <p>
        <%= form.label :propagation %><br>
        <%= form.text_area :propagation %>
    </p>
    <p>
        <%= form.label :growth_rate %><br>
        <%= form.text_area :growth_rate %>
    </p>
    <p>
        <%= form.label :max_size %><br>
        <%= form.text_area :max_size %>
    </p>
    <p>
        <%= form.label :interesting_facts %><br>
        <%= form.text_area :interesting_facts %>
    </p>
    <p>
        <%= form.submit %>
    </p>
   
  <% end %>

app/views/cacti/edit.html.erb
<h1>Edit Cactus</h1>

<%= form_with(model: @cactus, local: true) do |form| %>
    <p>
      <%= form.label :common_name %><br>
      <%= form.text_field :common_name %>
    </p>
    <p>
      <%= form.label :genus %><br>
      <%= form.text_field :genus %>
    </p>
    <p>
        <%= form.label :species %><br>
        <%= form.text_field :species %>
    </p>
    <p>
        <%= form.label :cultivar %><br>
        <%= form.text_field :cultivar %>
    </p>
    <p>
        <%= form.label :imageUrl %><br>
        <%= form.text_field :imageUrl %>
    </p>
    <p>
        <%= form.label :light_requirements %><br>
        <%= form.text_area :light_requirements %>
    </p>
    <p>
        <%= form.label :soil_requirements %><br>
        <%= form.text_area :soil_requirements %>
    </p>
    <p>
        <%= form.label :water_requirements %><br>
        <%= form.text_area :water_requirements %>
    </p>
    <p>
        <%= form.label :fruit %><br>
        <%= form.text_area :fruit %>
    </p>
    <p>
        <%= form.label :flower %><br>
        <%= form.text_area :flower %>
    </p>
    <p>
        <%= form.label :hardiness %><br>
        <%= form.text_area :hardiness %>
    </p>
    <p>
        <%= form.label :fertilizer %><br>
        <%= form.text_area :fertilizer %>
    </p>
    <p>
        <%= form.label :propagation %><br>
        <%= form.text_area :propagation %>
    </p>
    <p>
        <%= form.label :growth_rate %><br>
        <%= form.text_area :growth_rate %>
    </p>
    <p>
        <%= form.label :max_size %><br>
        <%= form.text_area :max_size %>
    </p>
    <p>
        <%= form.label :interesting_facts %><br>
        <%= form.text_area :interesting_facts %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

<%= link_to 'Home', cacti_path %>

app/views/cacti/index.html.erb
<h1>Cacti Collection</h1>

<%= link_to 'Add Cactus', new_cactus_url %>

<table>
    <% @cacti.each do |cactus| %>
        <tr>
            <th> Cactus: </th> 
            <td>
                <%= cactus.common_name %>- <%= cactus.genus %> <%= cactus.species %> <%= cactus.cultivar %> 
            </td>
        </tr>
        <tr>
            <th>Image</th>
            <td><%= image_tag cactus.imageUrl %></td>
        </tr>
        <tr>
            <th>Light Requirements</th> <td><%= cactus.light_requirements %></td>
        </tr>
        <tr>
            <th>Soil Requirements</th> <td><%= cactus.soil_requirements %></td>
        </tr>
        <tr>
            <th>Water Requirements</th> <td><%= cactus.water_requirements %></td>
        </tr>
        <tr>
            <th>Fruit</th> <td><%= cactus.fruit %></td>
        </tr>
        <tr>
            <th>Flower</th> <td><%= cactus.flower %></td>
        </tr>
        <tr>
            <th>Hardiness</th> <td><%= cactus.hardiness %></td>
        </tr>
        <tr>
            <th>Fertilizer</th> <td><%= cactus.fertilizer %></td>
        </tr>
        <tr>
            <th>Propagation</th> <td><%= cactus.propagation %></td>
        </tr>
        <tr>
            <th>Growth Rate</th> <td><%= cactus.growth_rate %></td>
        </tr>
        <tr>
            <th>Max Size</th> <td><%= cactus.max_size %></td>
        </tr>
        <tr>
            <th>Interesting Facts</th> <td><%= cactus.interesting_facts %></td>
        </tr>
        <tr>
            <th>Link</th> <td><%= link_to 'Show', cactus_path(cactus) %></td>
        </tr>
        <tr>
            <th>Link</th> <td><%= link_to 'Edit', edit_cactus_path(cactus) %></td>
        </tr>
        <tr>
            <th>Link</th> <td><%= link_to 'Destroy', cactus_path(cactus),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <tr class="extra_space">
            <th>Dummy Text</th>
            <td>Dummy Text</td>
        </tr>
    <% end %>
</table>

<%= link_to 'Add Cactus', new_cactus_url %>

app/views/cacti/new.html.erb
<h1>Add Cactus</h1>

<%= render 'form' %>

<%= link_to 'Home', cacti_path %>

app/views/cacti/show.html.erb
<p>
  <strong>Common Name:</strong>
  <%= @cactus.common_name %>
</p>
 
<p>
  <strong>Genus:</strong>
  <%= @cactus.genus %>
</p>

<p>
  <strong>Species:</strong>
  <%= @cactus.species %>
</p>

<p>
  <strong>Cultivar:</strong>
  <%= @cactus.cultivar %>
</p>

<p>
  <strong>ImageUrl:</strong>
  <%= @cactus.imageUrl %>
</p>

<p>
  <strong>Light Requirements:</strong>
  <%= @cactus.light_requirements %>
</p>

<p>
  <strong>Soil Requirements:</strong>
  <%= @cactus.soil_requirements %>
</p>

<p>
  <strong>Water Requirements:</strong>
  <%= @cactus.water_requirements %>
</p>

<p>
  <strong>Fruit:</strong>
  <%= @cactus.fruit %>
</p>

<p>
  <strong>Flower:</strong>
  <%= @cactus.flower %>
</p>

<p>
  <strong>Hardiness:</strong>
  <%= @cactus.hardiness %>
</p>


<p>
  <strong>Fertilizer:</strong>
  <%= @cactus.fertilizer %>
</p>


<p>
  <strong>Propagation:</strong>
  <%= @cactus.propagation %>
</p>


<p>
  <strong>Growth Rate:</strong>
  <%= @cactus.growth_rate %>
</p>


<p>
  <strong>Max Size:</strong>
  <%= @cactus.max_size %>
</p>

<p>
  <strong>Interesting Facts:</strong>
  <%= @cactus.interesting_facts %>
</p>

<%= link_to 'Home', cacti_path %> |
<%= link_to 'Edit Cactus', edit_cactus_path(@cactus) %> |
<%= link_to 'Add Cactus', new_cactus_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CactiCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>